<?php

echo 'Docker Commands';
echo "<br/>";
echo "=========================";
echo "<br/>";

echo "docker build -t friendlyname .  # Create image using this directory's Dockerfile";
echo "<br/>";
echo "docker run -p 4000:80 friendlyname  # Run \"friendlyname\" mapping port 4000 to 80";
echo "<br/>";
echo "docker run -d -p 4000:80 friendlyname         # Same thing, but in detached mode";
echo "<br/>";
echo "docker container ls                                # List all running containers";
echo "<br/>";
echo "docker container ls -a             # List all containers, even those not running";
echo "<br/>";
echo "docker container stop <hash>           # Gracefully stop the specified container";
echo "<br/>";
echo "docker container kill <hash>         # Force shutdown of the specified container";
echo "<br/>";
echo "docker container rm <hash>        # Remove specified container from this machine";
echo "<br/>";
echo "docker container rm $(docker container ls -a -q)         # Remove all containers";
echo "<br/>";
echo "docker image ls -a                             # List all images on this machine";
echo "<br/>";
echo "docker image rm <image id>            # Remove specified image from this machine";
echo "<br/>";
echo "docker image rm $(docker image ls -a -q)   # Remove all images from this machine";
echo "<br/>";
echo "docker login             # Log in this CLI session using your Docker credentials";
echo "<br/>";
echo "docker tag <image> username/repository:tag  # Tag <image> for upload to registry";
echo "<br/>";
echo "docker push username/repository:tag            # Upload tagged image to registry";
echo "<br/>";
echo "docker run username/repository:tag                   # Run image from a registry";

echo '<hr>';

echo "docker stack ls                                            # List stacks or apps";
echo "<br/>";
echo "docker stack deploy -c <composefile> <appname>  # Run the specified Compose file";
echo "<br/>";
echo "docker service ls                 # List running services associated with an app";
echo "<br/>";
echo "docker service ps <service>                  # List tasks associated with an app";
echo "<br/>";
echo "docker inspect <task or container>                   # Inspect task or container";
echo "<br/>";
echo "docker container ls -q                                      # List container IDs";
echo "<br/>";
echo "docker stack rm <appname>                             # Tear down an application";
echo "<br/>";
echo "docker swarm leave --force      # Take down a single node swarm from the manager";

echo '<hr>';

echo "docker-machine create --driver virtualbox myvm1 # Create a VM (Mac, Win7, Linux)";
echo "<br/>";
echo "docker-machine create -d hyperv --hyperv-virtual-switch \"myswitch\" myvm1 # Win10";
echo "<br/>";
echo "docker-machine env myvm1                # View basic information about your node";
echo "<br/>";
echo "docker-machine ssh myvm1 \"docker node ls\"         # List the nodes in your swarm";
echo "<br/>";
echo "docker-machine ssh myvm1 \"docker node inspect <node ID>\"        # Inspect a node";
echo "<br/>";
echo "docker-machine ssh myvm1 \"docker swarm join-token -q worker\"   # View join token";
echo "<br/>";
echo "docker-machine ssh myvm1   # Open an SSH session with the VM; type \"exit\" to end";
echo "<br/>";
echo "docker node ls                # View nodes in swarm (while logged on to manager)";
echo "<br/>";
echo "docker-machine ssh myvm2 \"docker swarm leave\"  # Make the worker leave the swarm";
echo "<br/>";
echo "docker-machine ssh myvm1 \"docker swarm leave -f\" # Make master leave, kill swarm";
echo "<br/>";
echo "docker-machine ls # list VMs, asterisk shows which VM this shell is talking to";
echo "<br/>";
echo "docker-machine start myvm1            # Start a VM that is currently not running";
echo "<br/>";
echo "docker-machine env myvm1      # show environment variables and command for myvm1";
echo "<br/>";
echo "eval $(docker-machine env myvm1)         # Mac command to connect shell to myvm1";
echo "<br/>";
echo "& \"C:\Program Files\Docker\Docker\Resources\bin\docker-machine.exe\" env myvm1 | Invoke-Expression   # Windows command to connect shell to myvm1";
echo "<br/>";
echo "docker stack deploy -c <file> <app>  # Deploy an app; command shell must be set to talk to manager (myvm1), uses local Compose file";
echo "<br/>";
echo "docker-machine scp docker-compose.yml myvm1:~ # Copy file to node's home dir (only required if you use ssh to connect to manager and deploy the app)";
echo "<br/>";
echo "docker-machine ssh myvm1 \"docker stack deploy -c <file> <app>\"   # Deploy an app using ssh (you must have first copied the Compose file to myvm1)";
echo "<br/>";
echo "eval $(docker-machine env -u)     # Disconnect shell from VMs, use native docker";
echo "<br/>";
echo "docker-machine stop $(docker-machine ls -q)               # Stop all running VMs";
echo "<br/>";
echo "docker-machine rm $(docker-machine ls -q) # Delete all VMs and their disk images";
